# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: pylmps

steps:

- script: |
    source source_me 
    cd tests/generic
    mpirun -np 2 python3 test_opt_hkust1.py
  displayName: 'testing pylmps MOF-FF opt'

- script: |
    source source_me 
    cd tests/xtb
    python3 test.py
  displayName: 'testing pylmps GFN1-xTB opt'

- script: |
    source source_me 
    cd tests/reaxff
    python3 test.py
  displayName: 'testing loose ReaxFF opt'
