#!/bin/bash

# Usage:
#  $ source /path/to/source_me


# Helper functions
function __print()
{
   if [ "$SILENT" == "0" ]; then
      echo $@
   fi
}

function __usage()
{
   echo "Usage: source source_me"
}

# Settings
SILENT=0

# Process command line
while [ "$1" != "" ]; do
   case $1 in
      --silent)
         SILENT=1
         ;;
      -h | --help )
         __usage
         return 1
         ;;
      * )
         __usage
         return 1
   esac
   shift
done

#
# Set paths
#

export PYLMPSPATH=`pwd`

__print "Set PATH to pylmps:" 
__print $PYLMPSPATH

export PYTHONPATH=$PYLMPSPATH:$PYTHONPATH
export PATH=$PYLMPSPATH/scripts:$PATH

#
# We assume default location for lammps and so on....
#
#LAMMPSPATH=/home/$USER/sandbox/lammps/python
#if [ -d $LAMMPSPATH ]; then 
#  export PYTHONPATH=LAMMPSPATH:$PYTHONPATH
#else
#  echo "Missing lammps installation"
#  exit 1
#fi
#
#LAMMPSPOT=/home/$USER/sandbox/lammps/potentials
#if [ -d $LAMMPSPOT ]; then
#   export REAXFF_FILES=$LAMMPSPOT
#else
#  echo "Missing lammps potentials"
#  exit 1
#fi
