#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to apply the ricfit analysis for a moelcular system
#
#########################################################################

#import ff_gen.IOmod as IOmod
import molsys.stow as stow
import molsys
import pylmps
import hessutils
import shutil
import numpy
import sys
import os
import copy
import pickle

mfpx = sys.argv[1]
name = mfpx.rsplit('.',1)[0]

if len(sys.argv) > 2:
    optimize=True
else:
    optimize=False


m = molsys.mol.from_file(mfpx)

m.addon('ff')
try:
    m.ff.read(name)
except:
    print('warning, reading FF with fit=True flag')
    m.ff.read(name,fit=True)
    
pl = pylmps.pylmps(name)
pl.setup(mol=m)

if optimize == True:
    ###  tbi: run optimization
    pass

hess = hessutils.doublehessian(pl);
hessian = hess()
hu = hessutils.hessutils(pl.get_xyz(),hessian,pl.get_elements())
hu.write_molden_input(name+'.freq')

pickle.dump(hessian,open('hessian.pickle','wb'))
